### ISSUE TITLE
Editor component MVP follow-up

### ISSUE THREAD

**Issue by hammer** [refstudio/refstudio#110]
- [x] #139
- [x] #131
- [x] #132
- [x] #133

**Comment by hammer** [comment]
New issue I encountered today: if I select all on the text in an editor window and then paste text over it, the editor window appears blank, but the text content is there, as it can be highlighted and shows up in the AI interactions window as selected text. Video below.

https://github.com/refstudio/refstudio/assets/15233/b7f0dc0d-845b-4265-aa12-c423e6e7ac32

**Comment by sehyod** [comment]
> Let's remove the full 2-pane layout for now and just allow PDFs to open into a separate read-only pane. We can revisit more complex layouts later when we're ready for more testing. Alternatively, we could consider adding a PDF reader as a 3rd element on the left sidebar, though that might be more complicated for now...

#105 should make side-by-side editors work properly, except when the same file is open twice (technically both editors work but the content is not synchronised). Maybe what we could do for now is just preventing opening the same file in two panes, I think it would be less work rather than having to redesign the internal state to have a write-only pane and a read-only pane.

**Comment by hammer** [comment]
👏🏽
