### ISSUE TITLE
Bullet and numbered list are not working

### ISSUE THREAD

**Issue by sehyod** [refstudio/refstudio#117]
> Bullet and numbered list don't work right now. Apparently it's just a CSS thing but it would be good to polish the editor experience a bit now.

From #110

**Comment by cguedes** [comment]
Found that the styles applied still don't look very nice

<img width="443" alt="image" src="https://github.com/refstudio/refstudio/assets/174127/42f942ab-363c-471b-9589-61f96865602f">

Noticed that the rule 

```css
.tiptap-editor ul,
ol {
  @apply pl-3;
}
```

is applying `pl-3` to `ol` globally instead of only inside the tiptap editor.
Also, I think we should use margin instead of padding for this rule (with `ml-7`)

Also, the spacing between list items happens because TipTap editor wraps content with `p` elements. 

The end result is nicer.

<img width="435" alt="image" src="https://github.com/refstudio/refstudio/assets/174127/aea5e30a-04d3-4ab3-a519-8224e0d87e9b">

Will send a PR for review @sehyod
