### ISSUE TITLE
Allow users to search and select references

### ISSUE THREAD

**Issue by hammer** [refstudio/refstudio#138]
In addition to PDF uploads, it would be nice if users could search and select references from something like the [Semantic Scholar (S2) API](https://api.semanticscholar.org/api-docs/graph).

**Comment by hammer** [comment]
@shauryr This video shows an example of how EndNote allows references to be added from an external reference database: https://youtu.be/S3xo6ZjBV6U?t=40. I'd of course want a better UX for our product, but hopefully you can get the general idea. I'd like to use S2 as our first external source. A lot of this work will be in the UI, I think (cc @cguedes @sehyod)

**Comment by shauryr** [comment]
@hammer thanks for sharing the video. It looks great. 
Semantic Scholar has a `search endpoint` where we can send our query and get the metadata of the paper -
[endpoint link](https://api.semanticscholar.org/graph/v1/paper/search?query=literature+graph&offset=0&limit=10&fields=title,venue,year
)
Here it will return 10 papers with the metadata` title, venue, year` but we can add more keys like `abstract` and `authors` if needed. We can also increase the size of the number of papers returned. If the paper is open access we can `wget` the paper and run grobid for full text extraction. 

I also want to add that the ranking of the search results is custom and is detailed here - [blog by Sergey](https://blog.allenai.org/building-a-better-search-engine-for-semantic-scholar-ea23a0b661e7) ; in practice exact title search is great, but for other queries it is not perfect, especially long queries will usually fail (limitation of there elasticsearch implementation). For our purposes it should be fine, and if we want to improve it we can later look into the SERP API.

**Comment by shauryr** [comment]
@gjreda I've made my first commit! - https://github.com/refstudio/refstudio/commit/b7d0adaa582750af1a80ddc825d26d29c9b6fa2f 
This script enables search functionality using S2 search endpoint. Please review and let me know if there are any improvements or changes you would suggest.

**Comment by cguedes** [comment]
@shauryr have you considered using https://github.com/danielnsilva/semanticscholar instead of RAW http request to the API?

**Comment by gjreda** [comment]
@shauryr Some general thoughts:
1. re: @hammer's comment about this living on the front-end, @cguedes and I think it's worth briefly discussing that on tomorrow's call. I could see it living in either place, but do think type-ahead should live on the front-end given our current architecture.
2. To @cguedes question, I think implementing this via the `semanticscholar` library would beneficial as it has a lot of built-in functionality for things like HTTP retries, exceptions, searching via specific fields, pulling down specific papers via unique IDs, etc. Rewriting all of that logic ourselves means more code for us to write, test, and maintain. It also seems pretty lightweight as a dependency, requiring only `requests` and `tenacity`, both of which are already needed for our inclusion of `openai` in our dependencies.
3. Based on tomorrow's chat, I think it'd be good to open up any backend work in need of review as a PR (and it's not "ready for review" yet, we can do a draft PR). I find commenting and discussion on PRs much easier to find later on, rather than having to find a specific commit hash.

**Comment by shauryr** [comment]
@gjreda Thank you for the feedback. I have created a PR for this considering all the feedback that I have received here.
 #250

**Comment by jvoytek** [comment]
@hammer I wasn't able to view the EndNote video above but I gave it a try anyway. Check out this [Figma Preview]( https://www.figma.com/proto/WgPkOwV2xyGpSjnS5xXfQZ/Semantic-Scholar-Search?type=design&node-id=1-915&t=69WcLglUOEqTodpg-0&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=13%3A235)

**Comment by jvoytek** [comment]
Image preview for reference...
![Screenshot 2023-09-13 at 11 39 55 AM](https://github.com/refstudio/refstudio/assets/8864493/347938cb-ab85-4ec3-a95c-4f64e673c2cc)
![Screenshot 2023-09-13 at 11 41 47 AM](https://github.com/refstudio/refstudio/assets/8864493/e374a3bc-6f1a-4b40-b5b8-8542867bf9af)

**Comment by hammer** [comment]
Oh cool I hadn't thought to use a modal for this interface! I presume we would disable summoning the command palette when this is up. I like the focus and increased screen real estate to display search results. Does the search happen after each keystroke, or does the user need to hit enter? I suppose we should make it possible to navigate to this modal from the command palette and from the sidebar too...

**Comment by jvoytek** [comment]
We could search after a debounced keystroke (not immediately, but once the user stops typing) and/or on "enter." I think it should be added wherever you can upload references. I need to play with this command palette.
