### ISSUE TITLE
Disable codecov annotations

### ISSUE THREAD

**Issue by gjreda** [refstudio/refstudio#251]
I find codecov annotations like the example below to be pretty distracting when reviewing a PR.

It looks like we can disable them: https://docs.codecov.com/docs/codecovyml-reference#github_checks-github-users-only

What do y'all think @cguedes @sehyod ?

<img width="705" alt="image" src="https://github.com/refstudio/refstudio/assets/921995/0b3b1215-3762-43b0-bc15-64f2088dfa68">

IMO if we want to know what lines are not covered by tests, we should do that separately directly within codecov's app (i.e. #187 )

**Comment by cguedes** [comment]
@gjreda we also don't like find them very useful ourselves. 
I've added the following setting in the [codecov global settings file](https://app.codecov.io/account/gh/refstudio/yaml). Maybe we should have it at the [project level instead](https://docs.codecov.com/docs/codecov-yaml).

<img width="1632" alt="image" src="https://github.com/refstudio/refstudio/assets/174127/cd57b19d-3c65-406f-940a-dad77676a270">

**Comment by cguedes** [comment]
@gjreda that configuration worked.

You can see that [this commit](https://github.com/refstudio/refstudio/runs/14807824920) don't have annotation and that [this previous one](https://github.com/refstudio/refstudio/runs/14806923759) has!

Would be nice to be able to configure the YAML only for this project, [here](https://app.codecov.io/gh/refstudio/refstudio/settings/yaml), but I can't edit online! Let me know if you can. Otherwise we can always create the config file in the project root dir.

<img width="1675" alt="image" src="https://github.com/refstudio/refstudio/assets/174127/64782237-44a2-444f-a1d4-a14f314b81e5">

**Comment by cguedes** [comment]
Just noting that one can also enable/disable annotations (per file) using this menu (also using shortcut `a`).

<img width="2056" alt="image" src="https://github.com/refstudio/refstudio/assets/174127/70b28851-4b15-4507-9f80-495d68bad99e">
