### ISSUE TITLE
Implement Tab/Shift-Tab for a non-empty selection

### ISSUE THREAD

**Issue by sehyod** [refstudio/refstudio#329]

**Comment by hammer** [comment]
@sehyod I think this has been implemented?

**Comment by sehyod** [comment]
No, indenting/unindenting does not work for non-empty selection yet. I need to think about it, I feel we can simply iterate through selected nodes and indent them individually but maybe there are edge cases. For unindent, it is trickier because unindenting a parent does already unindent the children so we need to iterate through parents only

**Comment by hammer** [comment]
Ah I see the "selection" part now. I think this issue interacts with https://github.com/refstudio/refstudio/issues/151, as in Notion it's more common to select at the block level rather than at the text level (i.e. by hitting "esc" first and then selecting things).

I'd love to get to https://github.com/refstudio/refstudio/issues/151 in the next week if possible. Let's discuss tomorrow!
