### ISSUE TITLE
[Discussion] Application State Management

### ISSUE THREAD

**Issue by cguedes** [refstudio/refstudio#33]
We should add application state management using [redux](https://react-redux.js.org/) and [redux toolkit](https://redux-toolkit.js.org/) to simplify the application data flow.

I like to use Redux for state management in React apps.
I'm not used to use Redux Toolkit (but like it enough) so I'm open to other options.
I've used redux-saga with success in other projects but I think it might be too much for us (or for now).

**Comment by cguedes** [comment]
@hammer @danvk @sergioramos @sehyod I've created this issue and the PR #30 with an implementation proposal (with other features).

**Comment by hammer** [comment]
I'm out of my depth here so I will let @danvk comment on whether this is a good idea. I have seen some commentary on [reducer and context](https://react.dev/learn/scaling-up-with-reducer-and-context) for lightweight state management without Redux, and I have also seen React-side libraries like React Query for server side state management (e.g. calls out to the AI from the editor) that may be in scope to discuss now?

**Comment by cguedes** [comment]
@hammer I think that our app will be complex enough to work with a state management library. But I agree that Redux can be too much.

@sergioramos pointed out that we can maybe use [Recoiljs](https://recoiljs.org/) instead. 

What are your thought on this @danvk?

**Comment by danvk** [comment]
@cguedes for recent projects I've used the built-in React state management (`useState`, very occasionally `useReducer`) and `react-query` to manage network calls. I have wound up using [reselect ](https://github.com/reduxjs/reselect) a few times when things got nasty. My sense is that Redux proper has become a bit less ubiquitous than it was, say, five years ago as the built-in state management tools have improved.

So my general inclination is similar to @hammer, that a fancy state management tool is something we can adopt as we feel the need for it. But things may have improved since I last used Redux and I've never used Reduce Toolkit, so I'll take a look at the PR!

**Comment by hammer** [comment]
@danvk notes that the future of Recoil is discussed at https://github.com/facebookexperimental/Recoil/issues/1495 with lots of recommendations to use https://github.com/pmndrs/jotai or https://github.com/pmndrs/zustand

**Comment by hammer** [comment]
Chatted with Eimen of Isaac Editor last night and he mentioned he's using `zustand` and loves it!

**Comment by cguedes** [comment]
https://jotai.org/docs/basics/comparison#how-is-jotai-different-from-zustand
https://github.com/pmndrs/jotai/issues/13

**Comment by hammer** [comment]
Lol nice to see we're in good company here: https://twitter.com/martpie_/status/1660198736880959490

**Comment by hammer** [comment]
Ha it turns out the guy who tweeted that is building a desktop app with Electron: https://github.com/martpie/museeks.

**Comment by cguedes** [comment]
> Ha it turns out the guy who tweeted that is building a desktop app with Electron: https://github.com/martpie/museeks.

I see that the project is using redux with toolkit.

https://github.com/martpie/museeks/blob/fcf12bd03a02911385f85d1196c6d09fe11a11de/package.json#L43

But working actively to move to Zustand (given that is similar to Redux IMO).

https://github.com/martpie/museeks/pull/675

> Jotai is like Recoil. Zustand is like Redux.

@hammer should we go with Jotai and merge #52 or you think we should also try Zustand? 
I suggest that we prioritize the implementation of a state management library for the main functionality without delay. We can then reassess the situation as the application grows.

**Comment by hammer** [comment]
I defer to y'all on Jotai vs. Zustand. @danvk I know you're off today but if you have any input I'd appreciate hearing it!

**Comment by martpie** [comment]
Hey folks!

> But working actively to move to Zustand (given that is similar to Redux IMO).

I can explain a bit my rationale if it can help you make a choice.

Redux is to Recoil what Zustand is to Jotai.

- Redux and Recoil are older, but more complete and are "proven"
- Zustand and Jotai are newer, and simpler
- [Jotai/Record are bottom-up while Redux/Zustand are top-down](https://jotai.org/docs/basics/comparison#how-is-jotai-different-from-zustand).

Why I am currently lending towards Zustand:

- I fell in love with [SolidJS's createStore](https://www.solidjs.com/tutorial/stores_createstore), which is very similar
- RTK is great, but still verbose
- My setup is a bit peculiar, as I historically started with Flux (before Redux even existed), and I used Actions as some kind of APIs (`PlayerAction.play()`, `PlaylistsActions.create()`, etc), so [my thunks are extremely weird blobs of getState + business logic](https://github.com/martpie/museeks/blob/master/src/renderer/store/actions/PlayerActions.ts#L109-L184)
- I love Zustand conciseness (actions+state together, no reducers). Zustand's model look similar to what I did (which does not mean my code is nice, it's not)
- Zustand has some very nice advanced features (store persistence, async out of the box, etc)
- Testing is easy-ish
- It will be MUCH easier to migrate from RTK to Zustand (paradigm is the same: stores + selectors) than something else.

Right now I'm just toying with it, but I'll probably stick with it :)

ps: Zustand and Jotai are from the same maintainers, they're not competitors, just two strategies to the same problem.

**Comment by sergioramos** [comment]
> BTW I also found [The new wave of React state management](https://frontendmastery.com/posts/the-new-wave-of-react-state-management/) to be a helpful overview 

I haven't finished reading but what I read so far is a fantastic piece. It explains well the context of React and state management tools, and why Redux **can be** a problematic solution (which I very much agree) 👏 will finish reading and share internally

**Comment by hammer** [comment]
Thanks you @martpie! Our general philosophy is to stay away from frameworks and try to keep things lightweight as long as possible so are leaning towards Jotai. Your input is very helpful!

**Comment by hammer** [comment]
@cguedes in the absence of negative feedback on Jotai and given our preference for something lightweight early on, let's go with that for now to unblock this issue.

**Comment by hammer** [comment]
@cguedes are we good to close this now that we've gone with Jotai?

**Comment by hammer** [comment]
Sounds good! Again if we're fighting the framework to code in a way that's less natural, I'm open to using something more Redux-like even if it's a bigger framework. RTK and Zustand both seem to be widely used and supported too.

**Comment by hammer** [comment]
BTW while doing a bit more digging I noticed that people seemed to like https://github.com/reduxjs/redux-devtools for debugging with Redux, and that Jotai has something similar at https://github.com/jotaijs/jotai-devtools, in case that hasn't turned up for y'all yet.

**Comment by sehyod** [comment]
Just to add a little more context to the discussion: I think we're not used to the Jotai approach, which is why we still have our doubts about it, but Jotai does come with some significant advantages, such as not having to manage stores or context and always being able to access atoms from any react component. And we can also save data in local storage directly with `atomWithStorage`.

**Comment by cguedes** [comment]
@hammer we think you can close this for now as we are more confident about Jotai 💪

**Comment by danvk** [comment]
Just a few thoughts looking at our use of Jotai a few weeks after committing to it (@cguedes mentioned at the meeting today that this is a part of the stack that not everyone's feeling great about)…

- Pros
  - Eliminates all the object spread / deep copying boilerplate that you see in Redux
  - It seems hard / impossible to have accidental state mutation, drop a rerender or access a stale version of some piece of state since you always have to go via `set` / `get`.
- Cons
  - The `get()` / `set()` syntax looks a little strange vs Redux's function composition
  - We wind up writing a lot of write-only atoms (though we'd be writing this logic in some form anyway)
  - There's no central (TypeScript) definition of the application's state

Would be interested to hear more from others if there are more specific pain points or examples of Jotai being awkward, but in general our code looks OK to me? There may be some opportunities to factor out common patterns (e.g. atom families) but I think it is succeeding at keeping our state management out of our UI code.
