### ISSUE TITLE
Error: `Bad CPU type in executable (os error 86)` when trying to use AI Selection feature

### ISSUE THREAD

**Issue by tmduarte98** [refstudio/refstudio#334]
When I was testing the released application I encountered an error, specifically when using the `Selection` feature. I selected some text and then requested the app to rewrite it but I got an error saying `Bad CPU type in executable (os error 86)`.

<img width="1704" alt="image" src="https://github.com/refstudio/refstudio/assets/47748693/33edbdb9-87b2-47bb-b53b-8d97be6cb21e">

I suspected it could be the version I was executing on my machine (Apple chip version on a Intel computer) but I checked the `.dmg` and it was the Intel version. Then I tried with the `universal` one, but unfortunately got the same error.

> **Note**: This doesn't happen on boot, only when using the `Selection` feature

For reference, this are the specs of my machine:
- OS Version: Ventura 13.4.1 (c)
- Chip: Intel Core i7

**Comment by cguedes** [comment]
Thanks for reporting the issue @tmduarte98 

I think that this might have to do with the [tauri sidecar integration](https://github.com/refstudio/refstudio/blob/adc02a8c074cdcc5c186dbf5c1416784179720c9/src-tauri/tauri.conf.json#L35) for intel chips.

**Comment by hammer** [comment]
@gjreda I forgot to bring this up today during the meeting! I've talked to a few people now who have hit this issue so if it's not a lot of work it would be nice to get it sorted.

**Comment by gjreda** [comment]
Dropping some notes here:
- [Tauri requires us](https://tauri.app/v1/guides/building/sidecar) to embed the Python application as an external binary and specify the `-$TARGET_TRIPLE` in the path declared within `tauri.conf.js`.
- We create the binary using PyInstaller, but PyInstaller is not a cross-compiler. It requires that you build the binary on the OS that you are targeting. From the [docs](https://pyinstaller.org/en/stable/): _"However, it is not a cross-compiler; to make a Windows app you run PyInstaller on Windows, and to make a Linux app you run it on Linux, etc."_
- It seems like we might be able to [use Github Actions to run PyInstaller and create OS-specific binaries](https://data-dive.com/multi-os-deployment-in-cloud-using-pyinstaller-and-github-actions/) for us

**Comment by gjreda** [comment]
Thinking about this a little more, I think we'd also need to move/create our release process using Github Actions.

I'm fairly sure the only reason the last (manual) release worked is because @cguedes had previously run `yarn python` before running `yarn tauri:build`. Tauri's build process then knew it had to include the Python binary from the specified path because it's declared in `tauri.config.js`, but nothing in our current build process includes creation of the Python binaries. 

So because our current build process is manual, and because builds require running PyInstaller, we'd only be able to support platforms that we develop on unless we make it part of our CI/CD pipelines.
