### ISSUE TITLE
Add missing API response types

### ISSUE THREAD

**Issue by cguedes** [refstudio/refstudio#510]
After #414 and #457 we still have some API responses missing in the generated `api-paths.ts`. 

The `POST /api/projects` is an example this.

https://github.com/refstudio/refstudio/blob/28e9047ba389b1030c4cd6dbfa8dd7bc3f7a6a4c/python/sidecar/projects/router.py#L27-L42

https://github.com/refstudio/refstudio/blob/28e9047ba389b1030c4cd6dbfa8dd7bc3f7a6a4c/src/api/api-paths.ts#L602-L622

**Comment by gjreda** [comment]
@cguedes I'll probably want to consolidate types quite a bit. For example, a lot of the project responses overlap pretty significantly, but are _slightly_ different than `ProjectDetailsResponse`. I'd like to avoid having many one-off types and prefer to have some general ones that can be uses across many endpoints.

Similarly, we have a bunch of `*Response` types that just have fields of `status, message, filepath`. I'd want to consolidate this rather than having specific ones for each endpoint.
