### ISSUE TITLE
[Discussion] Backend data model

### ISSUE THREAD

**Issue by gjreda** [refstudio/refstudio#8]
Working off of issue #6, I wanted to start a discussion around what we'll need for the backend database, mainly to make sure I'm wrapping my head around everything correctly.

Some high-level thoughts are below, but please add to it or suggest changes.

### Users
- I think this one is self-explanatory. Alternatively, I imagine we could call them Authors.

### Projects
- What the user works on in the WYSIWYG editor. Maybe alternatively called a Paper.
- Projects can have multiple users (ProjectUsers).
- Projects include zero to many ReferenceDocuments (ProjectDocuments).
- Projects include zero to many ChatInteractions.

### Documents
- Reference documents that are uploaded by a user.
- These are made up of many Chunks (which we'll create async after a document is uploaded).

### Chunks
- Portions of text from a given Document. Many chunks make up a Document.
- Embedding representations might be included here.

### ChatInteractions
- An interaction with the LLM about the Reference Documents.
- Many chat interactions make up an Interaction Thread (e.g. ChatGPT's sidebar)
- Chat interactions are made up of a input query (from user) and response (from LLM)

I imagine there might also be something like EditorInteractions, for when the LLM suggests a change or it's asked to title or summarize a block of text in the editor.

I also imagine we'll want to store edit history somehow.

**Comment by hammer** [comment]
To be honest I'd like to get to the MVP without a database. Single user, single document, references metadata and chunks and AI interactions kept in memory on the client. If we have to use a database, some kind of embedded database like sqlite would be nice for starters, though it doesn't appear to be supported by Supabase which seems like a frequently use wrapper to accelerate application development. I know doc chat makes use of vector databases so some kind of embedded vector database is fine too.

This issue is a great place to firm up terminology though! I think the thing the user is editing ("Project"/"Paper") is probably best referred to as "Document" or "Doc", as in "Word doc" or "Google doc". Then we could use "Reference" for each reference document.

For ChatInteractions, I wonder if "AIInteractions" will give us more flexibility in the UI, as the chat metaphor may not be the best UX for writing support.

**Comment by gjreda** [comment]
> To be honest I'd like to get to the MVP without a database. Single user, single document, references metadata and chunks and AI interactions kept in memory on the client. If we have to use a database, some kind of embedded database like sqlite would be nice for starters

This is helpful!

> I know doc chat makes use of vector databases so some kind of embedded vector database is fine too.

We don't necessarily need embeddings or a vector db for doc chat. For example, the [haystack prototype](https://github.com/gjreda/haystack-pdf-bot/blob/main/haystack_pdf_bot/main.py#L30) uses [BM25](https://en.wikipedia.org/wiki/Okapi_BM25#:~:text=BM25%20is%20a%20bag%2Dof,their%20proximity%20within%20the%20document.) for retrieval rather than a semantic approach. But we can also use something like FAISS, LanceDB, sqlite-vss, or possibly even [plain old numpy](https://www.ethanrosenthal.com/2023/04/10/nn-vs-ann/) for vector storage.

> it doesn't appear to be supported by Supabase which seems like a frequently use wrapper to accelerate application development

Ah, got it! My lack of modern front-end skills has me living in the days where you had some CRUD app server with postgres behind it.

> For ChatInteractions, I wonder if "AIInteractions" will give us more flexibility in the UI, as the chat metaphor may not be the best UX for writing support.

I agree. It's worth considering how to generalize this more.

**Comment by gjreda** [comment]
[Supabase also has the ability](https://supabase.com/docs/guides/getting-started/openai/vector-search) to use [pgvector](https://github.com/pgvector/pgvector) under the hood.

**Comment by gjreda** [comment]
This has been fixed by many commits over the last couple months and will be revisited once "launched."

For the prototype, we landed on a very simple backend using json stored on the filesystem. References and their metadata are stored in `.storage/references.json` and `sidecar/references/storage.py` acts as the API to interact with storage.
